version: '3.8'

services:
  master_db:
    image: postgres:15
    container_name: camate_master_db
    environment:
      POSTGRES_DB: master_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - master_db_data:/var/lib/postgresql/data

  ca_db_template:
    image: postgres:15
    container_name: camate_ca_template
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - ca_template_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: camate_redis
    ports:
      - "6379:6379"

volumes:
  master_db_data:
  ca_template_data: